language: csharp

sudo: required
dist: trusty

env:
  matrix:
    - FRAMEWORK=netcoreapp1.0
    - FRAMEWORK=net451

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get -y install dotnet-dev-1.0.0-preview2-003121

script:
  - dotnet --info
  - dotnet restore src test
  - dotnet test test/XRoadLib.Tests --framework $FRAMEWORK
