language: csharp

sudo: required
dist: trusty

env:
  matrix:
    - FRAMEWORK=netcoreapp1.1 FRAMEWORKPATH= TESTCOMMAND="dotnet test test/XRoadLib.Tests/XRoadLib.Tests.csproj --framework netcoreapp1.1 --configuration Debug"
    - FRAMEWORK=net452 FRAMEWORKPATH=/property:FrameworkPathOverride=/usr/lib/mono/4.5/ TESTCOMMAND="mono ~/.nuget/packages/xunit.runner.console/2.2.0/tools/xunit.console.exe test/XRoadLib.Tests/bin/Debug/net452/XRoadLib.Tests.dll"

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get -y install dotnet-dev-1.0.0-rc4-004771

script:
  - which mono
  - dotnet --info
  - dotnet restore test/XRoadLib.Tests/XRoadLib.Tests.csproj
  - dotnet build test/XRoadLib.Tests/XRoadLib.Tests.csproj --framework $FRAMEWORK --configuration Debug --verbosity detailed $FRAMEWORKPATH
  - $TESTCOMMAND
