language: csharp

sudo: required
dist: trusty

env:
  matrix:
    - FRAMEWORK=netcoreapp1.1
    - FRAMEWORK=net452

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get -y install dotnet-dev-1.0.0-rc4-004771

script:
  - which mono
  - dotnet --info
  - dotnet restore test/XRoadLib.Tests/XRoadLib.Tests.csproj
  - dotnet test test/XRoadLib.Tests/XRoadLib.Tests.csproj --framework $FRAMEWORK --configuration Debug /property:FrameworkPathOverride=/usr/lib/mono/4.5/
